name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sammobach/web-placeholder:${{ steps.branch_name.outputs.SOURCE_TAG }}
            sammobach/web-placeholder:latest
          build-args: |
            version=${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}